---
framework: jest
tier: small
postMerge: 
  pattern: 
    - 'packages/hoppscotch-app/**/__tests__/**/*.js'
    - 'packages/hoppscotch-js-sandbox/src/__tests__/**/*.ts'
preMerge:
  pattern:
    - 'packages/hoppscotch-app/**/__tests__/**/*.js'
    - 'packages/hoppscotch-js-sandbox/src/__tests__/**/*.ts'
preRun:
     command:
        - npm install -g pnpm
        - pnpm install
postRun:
     command:
        - node --version
version: 2.0
